name: ci_windows

env:
  CTEST_PARALLEL_LEVEL: 4
  CMAKE_BUILD_TYPE: Release

on:
  push:
    paths:
      - "**/CMakeLists.txt"
      - "**.cmake"
      - ".github/workflows/ci_windows.yml"
  pull_request:
  release:
    types: [published]


jobs:

  msys2:
    timeout-minutes: 30
    runs-on: windows-latest
    env:
      CMAKE_GENERATOR: Ninja

    strategy:
      matrix:
        shared: [true, false]

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          mingw-w64-x86_64-ninja
          mingw-w64-x86_64-gcc-fortran
          mingw-w64-x86_64-hdf5

    - name: Put MSYS2_MinGW64 on PATH
      run: echo "D:/a/_temp/msys64/mingw64/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - uses: actions/checkout@v2

    - run: cmake --preset multi -DCMAKE_INSTALL_PREFIX=${{ runner.temp }} -DBUILD_SHARED_LIBS:BOOL=${{ matrix.shared }}

    - run: cmake --build --parallel --preset debug
    - run: ctest --preset debug -V

    - run: cmake --build --parallel --preset release
    - run: ctest --preset release

    - run: cmake --install build

    - name: configure examples
      run: cmake -S Examples -B Examples/build -DCMAKE_PREFIX_PATH:PATH=${{ runner.temp }} -DBUILD_SHARED_LIBS:BOOL=${{ matrix.shared }}
    - name: build Examples
      run: cmake --build Examples/build --parallel
    - name: Test Examples
      run: ctest --test-dir Examples/build -V


# build works but takes a long time, so skip
  # msys2-build:
  #   timeout-minutes: 30
  #   runs-on: windows-latest
  #   env:
  #     CMAKE_GENERATOR: MinGW Makefiles

  #   strategy:
  #     matrix:
  #       shared: [true, false]

  #   steps:
  #   - uses: msys2/setup-msys2@v2
  #     with:
  #       update: true
  #       install: >-
  #         mingw-w64-x86_64-gcc-fortran

  #   - name: Put MSYS2_MinGW64 on PATH
  #     run: echo "D:/a/_temp/msys64/mingw64/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

  #   - uses: actions/checkout@v2

  #   - name: Configure HDF5
  #     run: cmake -S scripts -B scripts/build -DCMAKE_INSTALL_PREFIX=${{ runner.temp }} -DBUILD_SHARED_LIBS:BOOL=${{ matrix.shared }}

  #   - name: Build/install HDF5
  #     run: cmake --build scripts/build --parallel

  #   - name: configure h5fortran
  #     run: cmake -B build -DCMAKE_INSTALL_PREFIX=${{ runner.temp }} -DBUILD_SHARED_LIBS:BOOL=${{ matrix.shared }} -DCMAKE_PREFIX_PATH=${{ runner.temp }}

  #   - name: build h5fortran
  #     run: cmake --build build --parallel

  #   - name: test h5fortran
  #     run: ctest --test-dir build --preset default -V

  #   - run: cmake --install build
